
spring:
  application:
    name: eb-zuul-server
server:
  port: 8005
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
zuul:
  routes:
    order:
      path: /api-order/**
      serviceId: eb-order-server
    inventory:
      path: /api-inventory/**
      serviceId: eb-inventory-server
    sotrage:
      path: /api-storage/**
      serviceId: eb-storage-server


